# Introducción a NumPy

**NumPy** (*Numerical Python*) es una librería de Python diseñada para trabajar de forma eficiente con **datos numéricos** y realizar operaciones matemáticas.

Su estructura fundamental es el **array**, una colección ordenada de elementos que permite almacenar y manipular datos de forma eficiente. Los arrays de NumPy son especialmente útiles cuando tenemos grandes cantidades de datos y queremos realizar operaciones sobre ellos sin tener que trabajar elemento a elemento.

NumPy proporciona, entre otras funcionalidades:

* Creación y manipulación de arrays.
* Operaciones matemáticas y estadísticas.
* Generación de números aleatorios.
* Operaciones sobre vectores y matrices.
* Herramientas para trabajar con datos multidimensionales.

En este notebook veremos algunos de los conceptos básicos de NumPy que utilizaremos posteriormente para el **análisis de datos**.


In [1]:
import numpy as np

Un np.array es la estructura de datos principal de NumPy. Permite almacenar una colección de valores de forma ordenada y realizar operaciones matemáticas sobre ellos de manera eficiente.

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
print(x)

[1 2 3 4 5]


In [4]:
print(x.shape)
print(x.size)

(5,)
5


Los array pueden ser multidimensionales, por ejemplo:

In [5]:
x_2 = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
print(x_2)
print(x_2.shape)
print(x_2.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
6


Nos permiten realizar de forma sencilla operaciones vectoriales

In [7]:
#### Operaciones vectoriales
print(x + 10)
print(x * 2)
print(x ** 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [8]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

In [9]:
print(x + y) #### No puedo operar si tienen distintas dimensiones
print(x * y)

[11 22 33 44]
[ 10  40  90 160]


Tambien nos permite obtener estadisticos descriptivos de un array

In [10]:
print(np.mean(x))
print(np.std(x))
print(np.min(x))
print(np.max(x))
print(np.percentile(x, 50))

2.5
1.118033988749895
1
4
2.5


In [11]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 8, 10])

np.corrcoef(x, y)

array([[1.        , 0.99014754],
       [0.99014754, 1.        ]])

Podemos acceder a los valores de un array por su índice

In [14]:
print(x_2)

[[1 2 3]
 [4 5 6]]


In [12]:
print(x_2[0])
print(x_2[1, 2])
print(x_2[-1, -1])

[1 2 3]
6
6


In [15]:
print(x)

[1 2 3 4 5]


In [ ]:
print(x[1:3])

[2 3]


Python nos ofrece varias formas de interar sobre los valores de un array

In [ ]:
for value in x:
    print(value)

1
2
3
4


In [ ]:
for i in range(len(x)):
    print("When i is", i, "the value is", x[i])

When i is 0 the value is 1
When i is 1 the value is 2
When i is 2 the value is 3
When i is 3 the value is 4


Esto es util para ciertas operaciones, pero siempre sera más eficiente evitar los bucles

In [ ]:
x = np.array([1, 2, 3, 4, 5])
for i in range(len(x)):
    x[i] = x[i] * 2

print(x)

[ 2  4  6  8 10]


In [ ]:
x = np.array([1, 2, 3, 4, 5])
# Con NumPy
x = x * 2

print(x)

[ 2  4  6  8 10]


Una herramienta muy util es generar datos aleatorios que podeis usar para probar vuestros codigos y modelos. Aqui abajo os dejo como.

In [ ]:
np.random.seed(42) #### Cuando trabajeis con variables aleatorias, es recomendable fijar la semilla para que los resultados sean reproducibles. Probad a cambiar la semilla
x = np.random.normal(10, 2, 100)

print(x)

[10.99342831  9.7234714  11.29537708 13.04605971  9.53169325  9.53172609
 13.15842563 11.53486946  9.06105123 11.08512009  9.07316461  9.06854049
 10.48392454  6.17343951  6.55016433  8.87542494  7.97433776 10.62849467
  8.18395185  7.1753926  12.93129754  9.5484474  10.13505641  7.15050363
  8.91123455 10.22184518  7.69801285 10.75139604  8.79872262  9.4166125
  8.79658678 13.70455637  9.97300555  7.88457814 11.64508982  7.5583127
 10.41772719  6.08065975  7.3436279  10.39372247 11.47693316 10.34273656
  9.76870344  9.39779261  7.04295602  8.56031158  9.07872246 12.11424445
 10.68723658  6.47391969 10.64816794  9.22983544  8.646156   11.22335258
 12.06199904 11.86256024  8.32156495  9.38157525 10.66252686 11.95109025
  9.04165152  9.62868205  7.78733005  7.60758675 11.62505164 12.71248006
  9.85597976 12.0070658  10.72327205  8.70976049 10.72279121 13.07607313
  9.92834792 13.12928731  4.76050979 11.64380501 10.17409414  9.4019853
 10.18352155  6.02486217  9.56065622 10.71422514 12.95